# Grafana Datasource Configuration for Text-to-Audiobook Monitoring
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true